id: P118420CC
initial_creation_type: ocr
source_metadata:
  volumes:
    cfa40d7bdf8c48409557d013e2d9c896:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
